from .contactpoint import ContactPoint
from .data_distribution_service import DataDistributionService
from .dataset import PartialDataset
from .dcat_resource import PartialDcatResource
from .distribution import Distribution
from .harvest_meta_data import HarvestMetaData
from .publisher import PublisherId
from .quality_annotation import QualityAnnotation
from .references import Reference
from .skos_concept import SkosConcept
from .temporal import Temporal
