name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64
    - run: pip install virtualenv==20.2.1
    - run: pip install nox==2020.8.22
    - run: pip install poetry==1.1.3
    - run: pip install nox-poetry==0.5.0
    - run: nox --sessions tests coverage
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
