name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
        architecture: x64
    - run: pip install --constraint=.github/workflows/constraints.txt pip
    - run: pipx install --pip-args=--constraint=.github/workflows/constraints.txt poetry
    - run: pipx install --pip-args=--constraint=.github/workflows/constraints.txt nox
    - run: pipx inject --pip-args=--constraint=.github/workflows/constraints.txt nox nox-poetry
    - run: nox --sessions tests coverage
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
