name: Coverage
on: push
jobs:
  coverage:
    name: Coverage
    uses: Informasjonsforvaltning/workflows/.github/workflows/coverage-nox.yaml@main
    with:
      coverage_file_path: "./coverage.xml"
      python_version: "3.9"
      python_architecture: x64
      sessions: tests3_9
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
