name: Safety
on:
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install dependencies
      run: |
        pip install --constraint=.github/workflows/constraints.txt pip
        pipx install --pip-args=--constraint=.github/workflows/constraints.txt poetry
        pipx install --pip-args=--constraint=.github/workflows/constraints.txt nox
        pipx inject --pip-args=--constraint=.github/workflows/constraints.txt nox nox-poetry

    - name: Run safety
      id: safety
      run: |
        OUTPUT=$(echo "$(nox -s safety)")
        OUTPUT="${OUTPUT//'%'/'%25'}"
        OUTPUT="${OUTPUT//$'\n'/'%0A'}"
        OUTPUT="${OUTPUT//$'\r'/'%0D'}"
        echo "::set-output name=result::$OUTPUT"

    - name: Comment on PR with safety result
      if: github.event_name == 'pull_request' && ${{ inputs.run_safety }}
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: Safety result
        message: |
          ```
          ${{ steps.safety.outputs.result }}
          ```
