name: Safety
on:
  pull_request:
    branches:
      - main
jobs:
  safety:
    uses: Informasjonsforvaltning/workflows/.github/workflows/safety-nox.yaml@chore/hos/safety-formatting
    with:
      python_version: '3.9'
      python_architecture: x64
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
