name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - run: pip install nox==2020.8.22
    - run: pip install poetry==1.1.3
    - run: pip install nox-poetry==0.5.0
    - run: nox
