name: Tests
on: push
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    name: Python ${{ matrix.python-version }}
    uses: Informasjonsforvaltning/workflows/.github/workflows/test-nox.yaml@main
    with:
      python_version: ${{ matrix.python-version }}
      python_architecture: x64
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
